### ISSUE TITLE
Please add a clear method

### ISSUE THREAD

**Issue by bpj** [dagolden/Hash-Ordered#3]
Please add a clear method. `$oh->delete( $oh->keys )` is too expensive!

My use case is that I have a Hash::Ordered object as a ro member of another object,
so I'd like to be able to say `$other->oh->clear`.

**Comment by dagolden** [comment]
Great idea!  Want to send a pull request for it?  (With a test of course!)

**Comment by bpj** [comment]
Will do ASAP.

**Comment by dagolden** [comment]
Fixed with #4
