### ISSUE TITLE
merge reverses order

### ISSUE THREAD

**Issue by tomfy** [dagolden/Hash-Ordered#7]
When new is given an even sized list, if gives key/value pairs in the order given in the list, but merge reverses the order. Is there a reason for this? It certainly surprised me.

use Hash::Ordered;

my $A = Hash::Ordered->new(a => 1, b => 10);
for($A->keys()){
	print "$_  ", $A->get($_), "\n";
}
print "\n";

my $B = Hash::Ordered->new();
$B->merge(a => 1, b => 10);
for($B->keys()){
        print "$_  ", $B->get($_), "\n";
}

Output is:
a  1
b  10

b  10
a  1

**Comment by xdg** [comment]
Whoa.  No idea why it's like that.  Maybe just a "thinko" when I implemented it.

**Comment by xdg** [comment]
I'll get it fixed up next week.
